[package]
name = "path-reduction"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
lalrpop = "0.20.0"

[dependencies]
petgraph = "0.6.4"
byteorder = "1.4.3"
sha2 = "0.10.7"
hex = "0.4.3"
